// Punto de entrada único del sistema de diseño. Las pantallas importan solo desde aquí.
export { Alert } from './ui/alert'
export { Badge } from './ui/badge'
export { Button } from './ui/button'
export { Card, CardDescription, CardTitle } from './ui/card'
export { Field } from './ui/field'
export { AppShell, type NavItem } from './layout/app-shell'
export { AuthLayout } from './layout/auth-layout'
export { PageHeader } from './layout/page-header'
export { type ModuleKey } from './layout/module'
