# Generated by Django 5.2.17 on 2026-10-06 02:09

import apps.personas.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoDiscipular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('pide_maestro', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'proceso discipular',
                'verbose_name_plural': 'procesos discipulares',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('contacto', 'Contacto'), ('participante', 'Participante'), ('edu', 'Expediente completo')], default='contacto', max_length=20)),
                ('procedencia', models.CharField(choices=[('miembro', 'Miembro de la iglesia'), ('invitado_grupo', 'Invitado de grupo'), ('visitante', 'Visitante'), ('externo', 'Externo')], default='visitante', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, upload_to=apps.personas.models.foto_path)),
                ('whatsapp', models.CharField(blank=True, max_length=16, verbose_name='Celular / WhatsApp')),
                ('telefono_fijo', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('calle_numero', models.CharField(blank=True, max_length=200, verbose_name='calle y número')),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('alcaldia', models.CharField(blank=True, max_length=100, verbose_name='alcaldía o municipio')),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('grupo_conexion', models.CharField(blank=True, max_length=150)),
                ('lider', models.CharField(blank=True, max_length=150, verbose_name='líder')),
                ('miembro_desde', models.DateField(blank=True, null=True)),
                ('sirve_en_ministerio', models.BooleanField(default=False)),
                ('ministerios', models.TextField(blank=True, verbose_name='ministerio(s) en que sirve')),
                ('devocional_personal', models.CharField(blank=True, max_length=200)),
                ('oracion_familias', models.BooleanField(default=False, verbose_name='Oración de Familias en Acción (miércoles)')),
                ('oracion_familias_detalle', models.CharField(blank=True, max_length=200)),
                ('otros_cursos', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40)),
                ('acepta_datos', models.BooleanField()),
                ('acepta_foto', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='personas.persona')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PersonaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alta', 'Alta'), ('cambio_nivel', 'Cambio de nivel de registro'), ('baja', 'Baja'), ('reactivacion', 'Reactivación'), ('otro', 'Otro')], max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('motivo', models.CharField(blank=True, max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='personas.persona')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PersonaProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('maestro', models.CharField(blank=True, max_length=120, verbose_name='nombre del maestro')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='personas.persona')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='personas.procesodiscipular')),
            ],
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['nivel', 'activo'], name='personas_pe_nivel_80ad0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.UniqueConstraint(condition=models.Q(('whatsapp', ''), _negated=True), fields=('whatsapp',), name='persona_whatsapp_unico'),
        ),
        migrations.AddConstraint(
            model_name='personaproceso',
            constraint=models.UniqueConstraint(fields=('persona', 'proceso'), name='persona_proceso_unico'),
        ),
    ]
